### ISSUE TITLE
Initialize Laravel Capsule via ServiceProvider

### ISSUE THREAD

**Issue by namenu** [ridibooks/cms#18]
As a DI container, it'd be better to initialize `Capsule\Manager` using ServiceProvider.
There are several packages we can choose,
 - https://packagist.org/packages/ziadoz/silex-capsule
 - https://packagist.org/packages/bitolaco/silex-eloquent
 - https://packagist.org/packages/jguyomard/silex-capsule-eloquent

**Comment by imkitae** [comment]
`jguyomard/silex-capsule-eloquent` looks best, because it is the only one which depends on silex 2.x and is the most recently released project among the others.
